# Generated by Django 4.2.7 on 2023-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadSilla', models.PositiveIntegerField()),
                ('NumeroSala', models.CharField(max_length=7)),
                ('TamañoPantalla', models.CharField(max_length=30)),
                ('InclusividadSala', models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default=False)),
                ('TipoSala', models.CharField(choices=[('normal', 'Normal'), ('premiun', 'Premiun'), ('vip', 'Vip')], max_length=10)),
                ('EstadoSala', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], max_length=10)),
            ],
        ),
    ]
