# Generated by Django 4.2.7 on 2023-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='EstadoSala',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=10),
        ),
        migrations.AlterField(
            model_name='sala',
            name='InclusividadSala',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='si'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='TipoSala',
            field=models.CharField(choices=[('normal', 'Normal'), ('premiun', 'Premiun'), ('vip', 'Vip')], default='normal', max_length=10),
        ),
    ]
