# Generated by Django 4.2.7 on 2023-11-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_alter_sala_estadosala_alter_sala_inclusividadsala_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='TamañoPantalla',
            new_name='TamanioPantalla',
        ),
    ]
